health:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: itcast_health
    username: root
    password: 123456
  #阿里云oss配置
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJ3aT99J1gG9J3MVT3M
    access-key-secret: NBF9YPg8ywsTktRbNbOu2Cpui8dNRs
    bucket-name: tkzc00-bxg-health-parent
  # redis配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
