health:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: itcast_health
    username: root
    password: root
#阿里云oss配置
  alioss:
    endpoint: your endpoint address 例如 oss-cn-beijing.aliyuncs.com
    access-key-id: your access key
    access-key-secret: your access secret
    bucket-name: your bucket name
# redis配置
  redis:
    host: localhost
    port: 6379
#    password: 123456
    database: 10
